services:
  backend:
    build: ./backend
    ports:
      - "9001:9001"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
